version: 2
updates:
- package-ecosystem: maven
  directory: "/basic-test"
  schedule:
    interval: daily
    time: '08:00'
  open-pull-requests-limit: 99
- package-ecosystem: maven
  directory: "/basic-framework"
  schedule:
    interval: daily
    time: '08:00'
  open-pull-requests-limit: 99
