language: java

os: linux
  
dist: bionic

jdk:
  - openjdk8
  - openjdk11
  - openjdk14
  
addons:
  chrome: stable
  
cache:
  directories:
  - $HOME/.m2
  
script: "mvn -f selenium-basic-maven/pom.xml clean test"
