language: java

os: linux
  
dist: bionic

jdk:
  - openjdk11

env:
  - BROWSER_NAME=
  - BROWSER_NAME=firefox
  - BROWSER_NAME=chrome

addons:
  chrome: stable
  firefox: latest
  
cache:
  directories:
  - $HOME/.m2
  
script: "mvn -f selenium-basic-maven/pom.xml clean test"
