language: java

os: linux

dist: bionic

jdk:
  - openjdk11

env:
  - BROWSER_NAME=firefox
  - BROWSER_NAME=chrome

addons:
  chrome: stable
  firefox: latest

cache:
  directories:
    - $HOME/.m2

jobs:
  include:
    - stage: basic-test
      script: "mvn -f basic-test/pom.xml clean test"

    - stage: basic-framework
      script: "mvn -f basic-framework/pom.xml clean test"
