name: CI with Maven and Docker

on: [push, pull_request]

jobs:
  docker-build-basic-test-:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build --file "basic-test/Dockerfile" --tag edumco/basictest:latest "basic-test"
  
  docker-build-basic-framework:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build --file "basic-framework/Dockerfile" --tag edumco/framework:latest "basic-framework"
      
  maven-build-basic-test:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/basic-test/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: maven clean test
        run: mvn clean test --file basic-test/pom.xml

  maven-build-basic-framework:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**basic-framework/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Maven Test
        run: mvn clean test --file basic-framework/pom.xml
  
