name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  basic-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build --file "basic-test/Dockerfile" --tag edumco/basictest:latest "basic-test"
  
  basic-framework:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build --file "basic-framework/Dockerfile" --tag edumco/framework:latest "basic-framework"
