name: Build docker image

on: [push, pull_request]
 
jobs:
 docker-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.5
    - name: Build the Docker image
      run: docker buildx --file "basic-framework/Dockerfile" --tag edumco/selenium-examples :latest "basic-framework"
