name: Format Java Code

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - uses: axel-op/googlejavaformat-action@3.5.0
        with:
          args: "--set-exit-if-changed"
