name: Java build with maven

on: [pull_request]

jobs:
  maven-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['11', '17']
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          check-latest: true
          java-version: ${{ matrix.java }}
          
      - name: Cache Maven packages
        uses: actions/cache@v3.0.8
        with:
          path: ~/.m2
          key: ${{ runner.os }}-${{ matrix.java }}-m2-${{ hashFiles('**basic-framework/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-${{ hashFiles('**basic-framework/pom.xml') }}
          
      - name: Maven Test
        run: mvn clean test --file basic-framework/pom.xml
