name: CI with Maven

on: [push, pull_request]

jobs:
  basic-test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        env: [BROWSER_NAME: chrome, BROWSER_NAME: firefox]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/basic-test/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2 
      
      - name: maven clean test
        run: mvn clean test --file basic-test/pom.xml
        env: ${{ matrix.env }}

  basic-framework:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        env: [BROWSER_NAME: chrome, BROWSER_NAME: firefox]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**basic-framework/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2 
      
      - name: Maven Test
        run: mvn clean test --file basic-framework/pom.xml
        env: ${{ matrix.env }}
