name: Java build with maven

on: [push, pull_request]

jobs:
  maven-build-basic-framework:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v2.1.5
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**basic-framework/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Maven Test
        run: mvn clean test --file basic-framework/pom.xml
